### DISCUSSION TITLE
Multi-line `sh` steps from Jenkins retain outer quotes

### DISCUSSION THREAD

**Discussion by bewuethr** [github/gh-actions-importer#174] [Feedback] [answered]
For a minimal Jenkins pipeline such as

```groovy
pipeline {
  agent { label 'workers' }
  stages {
    stage('My stage') {
      steps {
        sh script: """
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --target prod \
            --build-arg go_version=${goVersion} \
            --tag sometag \
            --push \
            .
        """, label: 'My shell script'
      }
    }
  }
}
```

`gh actions-importer dry-run jenkins` produces this workflow:

```yaml
name: github-org/some-repo/main
on:
  workflow_dispatch:
jobs:
  My_stage:
    name: My stage
    runs-on:
      - self-hosted
      - workers
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: sh
      shell: bash
      run: |-
        """
                  docker buildx build \
                    --platform linux/amd64,linux/arm64 \
                    --target prod \
                    --build-arg go_version=${{ env.goVersion }} \
                    --tag sometag \
                    --push \
                    .
                """
```

The `"""` quotes really shouldn't be part of the output, though. Is this a bug in the built-in transformer for `sh`?
