### DISCUSSION TITLE
[Azure DevOps -> GitHub] parameters for manual runs aren't converted correctly

### DISCUSSION THREAD

**Discussion by thunermay** [github/gh-actions-importer#309] [Feedback]
I am in the process of migrating our pipelines from ADO to GH. After doing some dry-runs I encountered an issue. This is a part of the ADO-`yaml`:
```
parameters:
- name: Env
  type: string
  default: prod #can pass multiple values separated by a comma.
  values:
  - dev
  - int
  - prod
```
And this is the result from the `github actions-importer`:
```
on:
  workflow_dispatch:
    inputs:
      Env:
        default: prod
        type: string
        required: false
```

At first, I thought it wouldn't be possible to have a list of options but I found [this](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#providing-inputs) article describing inputs to a manual trigger. To my understanding, the correct parsing would be as follows:
```
on:
  workflow_dispatch:
    inputs:
      Env:
        default: prod
        required: false
        type: choice
        options:
        - dev
        - int
        - prod
```

Am I wrong or does it need fixing?

best regards
