### ISSUE TITLE
[Feature]: Gitlab container image name references need to be resolved

### ISSUE THREAD

**Issue by Daniel-Klockenkaemper** [github/gh-actions-importer#10]
### What operating system are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### What version of the tool are you using?

gh version 2.20.2 (2022-11-15)
gh actions-importer github/gh-actions-importer v1.0
actions-importer/cli v1.0.14322

### What happened?

When importing Gitlab CI configurations container name references are replaced by environment variables, which does not work. Instead they may be resolved and replaced by the resulting string.

Example: 
```
# Gitlab configuration:
variables:
  BUILDER_IMAGE: xxx.com/yyyy:latest
...

build:
  image:
    name: $BUILDER_IMAGE
...

# Resulting GitHub workflow configuration:
jobs:
  build:
    container:
      image: "$BUILDER_IMAGE"
    env:
      BUILDER_IMAGE: xxx.com/yyyy:latest
...

# Desired GitHub workflow configuration:
jobs:
  build:
    container:
      image: "xxx.com/yyyy:latest"
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
