### ISSUE TITLE
[Support] Azure pipeline conversion mapping for step template 

### ISSUE THREAD

**Issue by Poonnaphop-Ben** [github/gh-actions-importer#157]
Currently we have created a step template for ADO that will be use by multiple Azure pipelines; Example syntax below

```
resources:
  repositories:
    - repository: reusable_modules
      type: github
      name: {organiation/repository}
      ref: {tag-versions}
      endpoint: {service-connection-name}
...
    steps:
      - template: main.yml@reusable_modules
        parameters:
          clientID: "$(clientID)"
          clientSecret: "$(clientSecret)"
          path: '.'
```
We've also created central composite actions as a reusable module inside GitHub, that have a similar functionality with the step template in ADO. However, by default it seem that when running the conversions the step templates will be convert to a new composite actions.

In this case, Is it possible to map the step template in ADO to an existing composite actions, instead of converting to a new composite action? Can we use a custom transformer to map between the template and existing composite actions? 

Additional info: 
Running gh-actions-importer on GitHub Hosted runner (ubuntu-latest):
```
runner version: '2.304.0'
ghcr.io/actions-importer/cli:1.3.18876
```

**Comment by Chaseshak** [comment]
Hi @Poonnaphop-Ben

This appears to be a bug with how we reference composite actions in other repositories. The `.github/actions` is only intended to be appended for local composite actions.

I've pushed a fix to a pre-release image that should resolve this issue. Can you test it out and let me know if it works for you?

```shell
gh actions-importer update --prerelease
# Verify the install is correct
gh actions-importer version --prerelease
# Should output actions-importer/cli:pre v1.3.45
```

Then you'll need to run your commands with the `--prerelease` (e.g. `gh actions-importer dry-run azure-devops --prerelease ...` flag appended for now. If it works for you we'll get this shipped shortly so you don't have to use the `--prerelease` option.

Separately, I've also added support for a `subdirectory:` option to the custom composite actions in the config file in case you have multiple composite actions contained in one repository:
```yml
composite_actions:
  - name: my_template
    target_url: https://github.com/chaseshak/composite-action-example
    ref: main
    subdirectory: my/dir # This is optional and must contain an action.yml file
``` 

Which would result in a uses statement like `uses: chaseshak/composite-action-example/my/dir@main`

Please let me know if this resolves your issue!

**Comment by Chaseshak** [comment]
@Poonnaphop-Ben We've released this change in the latest deploy. Run `gh actions-importer update` to pull the new container.

The only change from my note above is that we renamed the `subdirectory:` option to `path:`.

Please see some examples below and let me know if you have any additional questions!
```yaml
# Usage examples
composite_actions:
# 1. Local composite action in actions folder (Default)
# Results in `uses: ./.github/actions/my_template`
- name: my_template
  ref: main
# 2. Local composite action in another directory
# Results in `uses: ./path/to/action`
- name: my_template
  ref: main
  path: path/to/action
# 3. Remote repository with composite action at the root of the repository
# Results in `uses: org/repo@ref`
- name: my_template
  target_url: https://github.com/org/repo
  ref: main
# 4. Remote repository with composite action in another directory
# Results in `uses: org/repo/path/to/action@ref`
- name: my_template
  target_url: https://github.com/org/repo
  ref: main
  path: path/to/action
```

**Comment by Poonnaphop-Ben** [comment]
Hi @Chaseshak , sorry for the late respond. 

I have tested the new versions for the actions-importer, although I was using the docker image one that seem to got the new versions update recently `ghcr.io/actions-importer/cli:1.3.19302`.  And I can confirmed that it is working like a charm! 

Thank you very much for the promptly update!

However, this might be a long shot but would there be an enhancement for the config path in order to map between the source ADO template parameters to the target composite action? I understand that this might not be an intention for the config path however we got some example here:

``` yaml
composite_actions:
  - name: my_template
    target_url: https://github.com/org/repo
    ref: main
    with:
      target_parameter: source_parameter
```

Feel free to close this issue as well, as the current config path is working as intended.
