### ISSUE TITLE
Custom transformer for manual_task using gh actions-importer

### ISSUE THREAD

**Issue by michaelfindlater** [github/gh-actions-importer#164]
Hi there. We're trying to create a custom transformer for the `gh actions-importer` to migrate a CircleCI workflow to GitHub Actions.

The CircleCI workflow has a step as follows:
```yaml
    steps:
...
      - setup_remote_docker:
          docker_layer_caching: true
...
```

Without a transformer, this step produces the following error:
```
undefined method `manual_tasks' for #<Transformers::Result::Unsupported:0x00007f278aeee568 @identifier="setup_remote_docker", @comment="'setup_remote_docker' was not transformed because there is no suitable equivalent in GitHub Actions", @snippet=nil, @dependencies=[]>
```

What we want to do is skip this step, during translation, if it exists in the CircleCI workflow being translated.

We've _tried_ to create a custom transformer to do this. Here's the code for that transformer:
```ruby
transform "setup_remote_docker" do |_item|
  nil
end
```

With this, we get the following error:
```
undefined method `manual_tasks' for #<Transformers::Result::Custom:0x00007fa7dd6af298 @identifier="setup_remote_docker(custom)", @comment=nil, @snippet=nil, @dependencies=[]>
```

We don't fully understand how to write custom transformers for what seem to be called "manual tasks". We've read the [docs](https://docs.github.com/en/actions/migrating-to-github-actions/automated-migrations/extending-github-actions-importer-with-custom-transformers#creating-custom-transformers-for-items) and looked at the [codelab examples](https://github.com/actions/importer-labs/blob/main/circle_ci/5-custom-transformers.md) but are still lost.

- How can we write a custom transformer for a manual task?
- Is the source code for the custom transformer part of actions-importer available? Was hoping to use this to debug, but couldn't find it.

Thanks!

**Comment by j-dunham** [comment]
Hi @michaelfindlater,  The manual task is not something you would add a custom transformer for, it a internal structure used to add tasks to the PR created from the `migrate` command.  That being said I think your issue is something different.  The custom transformer you provided is valid and the `setup_remote_docker` is not supported and should generate only a comment in the outputted workflow, even without the custom transformer.  Can you provide more of the CircleCI workflow so I can investigate further and the logs? Make sure to remove any personal information. 

If you are curious I confirmed the custom transformer worked by using the `--source-file-path` to use a simple local workflow.

circle_config.yaml
```yaml
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "Hello, world!"
      - setup_remote_docker:
          version: 20.10.14

workflows:
    example-workflow:
      jobs:
        - build
```

transformer.rb
```yaml
transform "setup_remote_docker" do |_item|
  {
    "name" => "Setup Remote Docker",
    "run" => "echo 'Setup Remote Docker'",
  }
end
```
example command
```
gh actions-importer dry-run circle-ci --circle-ci-project circle-demo -o tmp/dry-run --source-file-path tmp/circle_config.yml --custom-transformers tmp/transformer.rb
```
