### ISSUE TITLE
[Support]: Matrix converted from azure-devops is incomplete and out of order.

### ISSUE THREAD

**Issue by akb825** [github/gh-actions-importer#24]
### What operating system are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### What version of the tool are you using?

gh version 2.20.2 (2022-11-15)
gh actions-importer     github/gh-actions-importer      v1.0
actions-importer/cli    v1.0.14451

### What happened?

When converting pipelines from azure-devops with a matrix of build options, the options are often incomplete and out of order. This seems to happen when options are duplicated, perhaps using a shared map or set between all of the entries?

For example, this was the input matrix from one of my azure-devops pipelines:
```
        matrix:
            win32_static:
                arch: Win32
                libs: win32
                lib.type: Static
                cmake.args: -DDEEPSEA_SHARED=OFF
            win32_shared:
                arch: Win32
                libs: win32
                lib.type: Shared
                cmake.args: -DDEEPSEA_SHARED=ON
            win32_single_shared:
                arch: Win32
                libs: win32
                lib.type: Single-Shared
                cmake.args: -DDEEPSEA_SINGLE_SHARED=ON
            win64_static:
                arch: x64
                libs: win64
                lib.type: Static
                cmake.args: -DDEEPSEA_SHARED=OFF
            win64_shared:
                arch: x64
                libs: win64
                lib.type: Shared
                cmake.args: -DDEEPSEA_SHARED=ON
            win64_single_shared:
                arch: x64
                libs: win64
                lib.type: Single-Shared
                cmake.args: -DDEEPSEA_SINGLE_SHARED=ON
```

The following output was generated:
```
      matrix:
        include:
        - arch: Win32
          libs: win32
          lib.type: Static
          cmake.args: "-DDEEPSEA_SHARED=OFF"
        - arch: Win32
        - arch: x64
          lib.type: Shared
          cmake.args: "-DDEEPSEA_SHARED=ON"
        - arch: Win32
        - arch: x64
          lib.type: Single-Shared
          cmake.args: "-DDEEPSEA_SINGLE_SHARED=ON"
        - arch: x64
          libs: win64
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
