### ISSUE TITLE
[Support] Azure Pipeline conversaion fails because of bad template url

### ISSUE THREAD

**Issue by gburketkxs** [github/gh-actions-importer#58]
Running gh-actions-importer on Windows using:
```
gh version 2.23.0 (2023-02-08)
gh actions-importer     github/gh-actions-importer      v1.1.0
actions-importer/cli:latest     v1.1.16605
```

Almost all of my azure devops pipelines reference a repo with common yml templates for builds and deployments in it.  When i attempt to do an audit with the actions importer they all produce the same error when attempting to pull the ylm from the template repo.

Here is the syntax used for the base yml in the repo to reference the template repo and individual yml files within it:
```
resources:
  repositories:
    - repository: '<alias>' #alias name
      type: git #type of repository
      name: <repo name> #repository name
      ref: 'refs/heads/template' #git branch reference
...
- template: <yml template file name>@<alias>
      parameters:
        dependson: <dependancy>
        environmentCustomFieldName: Dev
```

the importer fails because it generates this url for the template...
here is the error:
```
Message: Resource not found
(GET 404) Not Found: https://dev.azure.com/<organization name>/<repo name>/_apis/git/repositories//items?api-version=5.0-preview&path=<referenced yml file name>&versionDescriptor.version=<branch name>
```

but the url should be this...
```
https://dev.azure.com/<organization name>/<project name>/_apis/git/repositories/<repo name>/items?api-version=5.0-preview&path=<referenced yml file name>&versionDescriptor.version=<branch name>
```

it appears to be putting the repo name where the project goes, and nothing where the repo name is supposed to go.
