### ISSUE TITLE
[Feature]: Gitlab regex comparison expression is not correctly replaced

### ISSUE THREAD

**Issue by Daniel-Klockenkaemper** [github/gh-actions-importer#9]
### What operating system are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### What version of the tool are you using?

gh version 2.20.2 (2022-11-15)
gh actions-importer github/gh-actions-importer v1.0
actions-importer/cli v1.0.14322

### What happened?

When importing Gitlab CI configurations the regex comparison expression `=~` is not replaced. This expression is currently not supported by GitHub. We could instead replace it to something like `contains()`. We could get this even further when using `startsWith()` or `endsWith()` depending on the regex values configured.

Example:
```
# original expression:
  except:
    refs:
      - master
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Merge tag.*/

# output:
if: !(github.ref == 'refs/heads/master' && $CI_COMMIT_MESSAGE =~ /^Merge tag.*/)

# desired output:
if: !(github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, 'Merge tag'))

# or even better
if: !(github.ref == 'refs/heads/master' && startsWith(github.event.head_commit.message, 'Merge tag'))
```

(The replacement of $CI_COMMIT_MESSAGE is separated to #8)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
